name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for reporting an issue. Make sure that you described the problem thoroughly and included the required steps to reproduce the problem."
        pr-message: "Thanks for your contribute, the owner will soon look into it. And if it's complete and ready, they will also merge it."
